# Generated by Django 4.2.25 on 2025-12-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('academic_status', models.CharField(max_length=50)),
                ('skills', models.TextField(blank=True, null=True)),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('verification_status', models.BooleanField(default=False)),
            ],
        ),
    ]
