# Generated by Django 4.2.27 on 2026-01-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_location',
            field=models.TextField(blank=True, help_text='Meeting Link or Physical Address', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_mode',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50, null=True),
        ),
    ]
