# Generated by Django 4.2.27 on 2026-01-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_application_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='interview_location',
        ),
        migrations.RemoveField(
            model_name='application',
            name='interview_mode',
        ),
    ]
