# Generated by Django 4.2.27 on 2026-01-24 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_application_status_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_role', models.CharField(choices=[('student', 'Student'), ('employer', 'Employer')], max_length=10)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='student.application')),
            ],
        ),
        migrations.RemoveField(
            model_name='skillservice',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='skillservice',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
