# Generated by Django 4.2.27 on 2025-12-17 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MyApp', '0004_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('employer_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='MyApp.district')),
                ('address', models.TextField()),
                ('verification_status', models.BooleanField(default=False)),
            ],
        ),
    ]
