# Generated by Django 4.2.27 on 2026-01-03 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_location'),
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='MyApp.district'),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='MyApp.location'),
        ),
    ]
