# Generated by Django 4.2.27 on 2026-01-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_student_district_student_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='district',
        ),
        migrations.RemoveField(
            model_name='student',
            name='location',
        ),
    ]
