# Generated by Django 4.2.27 on 2026-01-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_subscriptionplan_employer_jobs_posted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='jobs_posted',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='subscription_status',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='trial_end_date',
        ),
        migrations.AddField(
            model_name='employer',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.TextField(blank=True, help_text='About the company'),
        ),
        migrations.AddField(
            model_name='employer',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, help_text='Short professional summary'),
        ),
        migrations.AddField(
            model_name='student',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
