# Generated by Django 6.0.1 on 2026-01-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0008_delete_jobposting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='district',
        ),
        migrations.AddField(
            model_name='employer',
            name='area',
            field=models.CharField(default='Kochi', help_text='e.g., Kaloor, Kochi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='industry',
            field=models.CharField(default='General', help_text='e.g., Retail, Education', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='availability',
            field=models.CharField(default='Flexible', help_text='e.g., Weekends, After 5 PM', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_roles',
            field=models.CharField(blank=True, help_text='e.g., Sales, Data Entry', max_length=200),
        ),
    ]
