# Generated by Django 6.0.1 on 2026-01-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0009_remove_employer_district_employer_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='employer',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
