# Generated by Django 4.2.27 on 2026-01-16 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_delete_location'),
        ('guest', '0011_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='portfolio_link',
        ),
        migrations.AddField(
            model_name='employer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.district'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.district'),
        ),
    ]
