# Generated by Django 4.2.27 on 2026-01-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0014_report_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
