# Generated by Django 4.2.27 on 2026-01-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0014_report_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_status',
            field=models.CharField(choices=[('diploma', 'Diploma'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('passout', 'Pass-out')], default='undergraduate', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='availability',
            field=models.CharField(choices=[('weekdays_evening', 'Weekdays (Evening)'), ('weekends', 'Weekends'), ('flexible', 'Flexible'), ('10_15_hrs', '10-15 hrs/week')], default='flexible', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_roles',
            field=models.CharField(blank=True, help_text='Multi-select: Web Developer, Tutor, etc.', max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
