# Generated by Django 4.2.27 on 2026-01-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0015_student_course_name_student_institution_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
