# Generated by Django 4.2.27 on 2026-01-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0015_student_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='area',
            field=models.CharField(blank=True, help_text='e.g., Kaloor, Kochi', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='industry',
            field=models.CharField(blank=True, default='General', help_text='e.g., Retail, Education', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='availability',
            field=models.CharField(blank=True, default='Flexible', help_text='e.g., Weekends, After 5 PM', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_roles',
            field=models.CharField(blank=True, help_text='e.g., Sales, Data Entry', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
