# Generated by Django 4.2.27 on 2026-01-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0016_alter_employer_address_alter_employer_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
