# Generated by Django 4.2.27 on 2026-02-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0017_student_date_of_birth'),
        ('guest', '0018_alter_student_bio'),
    ]

    operations = [
    ]
