# Generated by Django 4.2.27 on 2026-02-04 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_delete_location'),
        ('guest', '0019_merge_20260204_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.category'),
        ),
    ]
