# Generated by Django 4.2.27 on 2026-01-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='skills_required',
            field=models.TextField(default='', help_text='List required skills separated by commas'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='working_hours',
            field=models.CharField(default='8 hours/day', help_text='e.g., 8 hours/day, 4 hours/day, Flexible', max_length=100),
        ),
    ]
