# Generated by Django 4.2.27 on 2026-01-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_jobposting_skills_required_jobposting_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, help_text='Required for Offline jobs', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='work_mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='working_hours',
            field=models.CharField(default='Part Time', help_text='e.g., 10 hours/week', max_length=100),
        ),
    ]
