# Generated by Django 6.0.1 on 2026-01-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_jobposting_is_active_alter_jobposting_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='work_mode',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='hourly_pay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rate per hour', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='part_time_category',
            field=models.CharField(choices=[('weekend', 'Weekend Only'), ('evening', 'Evening Shift'), ('event', 'Event / One-time'), ('remote', 'Freelance / Remote'), ('flexible', 'Flexible Hours'), ('other', 'Other')], default='flexible', max_length=50),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='shift_timing',
            field=models.CharField(default='Flexible', help_text='e.g., 6 PM - 10 PM', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='working_days',
            field=models.CharField(default='Flexible', help_text='e.g., Saturday & Sunday', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
