# Generated by Django 4.2.27 on 2026-01-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_remove_jobposting_work_mode_jobposting_hourly_pay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='skills_required',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_type',
            field=models.CharField(choices=[('online', 'Online / Remote'), ('offline', 'Offline / On-site')], default='offline', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
