# Generated by Django 4.2.27 on 2026-02-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='hourly_pay',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per hour', max_digits=10, null=True),
        ),
    ]
