# Generated by Django 4.2.27 on 2026-02-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_alter_jobposting_hourly_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='requirements',
            field=models.TextField(blank=True, help_text='Key Responsibilities and Requirements', null=True),
        ),
    ]
