# Generated by Django 4.2.27 on 2026-02-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_jobposting_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='free_trial_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_free_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_days',
            field=models.IntegerField(default=14),
        ),
    ]
