# Generated by Django 4.2.27 on 2026-02-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_subscription_free_trial_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan_name',
            field=models.CharField(choices=[('basic', 'Basic Plan'), ('sponsor', 'Sponsor Plan'), ('premium', 'Premium Plan'), ('enterprise', 'Enterprise Plan')], default='basic', max_length=50),
        ),
    ]
