# Generated by Django 4.2.25 on 2025-12-12 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_districts',
            new_name='District',
        ),
    ]
