# Generated by Django 6.0.1 on 2026-01-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_category_id_alter_district_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.RemoveField(
            model_name='district',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='district',
            name='district_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
