# Generated by Django 4.2.27 on 2026-01-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_remove_category_id_remove_district_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
