# Generated by Django 4.2.25 on 2025-12-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_employer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
